double_options:
  adaptive_rho_fraction: 0.4
  adaptive_rho_tolerance: 5
  alpha: 1.2
  delta: 1.0e-05
  eps_abs: 1e-4
  eps_dual_inf: 1e-4
  eps_prim_inf: 1e-4
  eps_rel: 1e-4
  rho: 600
  sigma: 1.0e-08
  time_limit: 3.0
int_options:
  adaptive_rho: 1
  adaptive_rho_interval: 0
  check_termination: 950
  max_iter: 50000
  polish: 0
  polish_refine_iter: 9
  scaled_termination: 1
  scaling: 32
  verbose: 0
  warm_start: 1
log_file_name: ''
print_to_console: 0
string_options: {}
